In [2]:
import os
os.chdir('D:\JypyterNotebookCode\\SupervisedLearning\\iris dataset\\')

In [3]:
os.getcwd()

'D:\\JypyterNotebookCode\\SupervisedLearning\\iris dataset'

In [4]:
import pandas as pd
import numpy  as np

In [5]:
dataset = pd.read_csv('iris.csv')

In [6]:
dataset

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [51]:
x=dataset.iloc[:,1:4].values

In [28]:
y=dataset.iloc[:,4].values

In [53]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [54]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [55]:
x

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.1, 1.5, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3

In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [57]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

LogisticRegression()

In [58]:
y_pred = logmodel.predict(x_test)

In [59]:
y_pred

array([2, 0, 1, 0, 0, 2, 1, 1, 1, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1,
       2, 0, 2, 2, 0, 2, 2, 1], dtype=int64)

In [60]:
y_test

array([2, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1,
       2, 0, 2, 2, 0, 2, 2, 1], dtype=int64)

In [63]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  2,  9]], dtype=int64)

In [64]:
28/30

0.9333333333333333

In [70]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [72]:
y_pred = classifier_knn.predict(x_test)

In [73]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 10]], dtype=int64)

In [74]:
29/30

0.9666666666666667

In [75]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train)

GaussianNB()

In [76]:
y_pred = classifier_nb.predict(x_test)

In [77]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 10]], dtype=int64)

In [83]:
29/30

0.9666666666666667

In [79]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train, y_train)

SVC(kernel='sigmoid')

In [87]:
y_pred = classifier_svm_sigmoid.predict(x_test)

In [88]:
confusion_matrix(y_test,y_pred)

array([[ 2, 10,  0],
       [ 0,  7,  0],
       [ 8,  3,  0]], dtype=int64)

In [91]:
7/30

0.23333333333333334

In [92]:
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(x_train, y_train)

SVC(kernel='linear')

In [93]:
y_pred = classifier_svm_linear.predict(x_test)

In [94]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 10]], dtype=int64)

In [95]:
29/30

0.9666666666666667

In [97]:
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train, y_train)

SVC()

In [98]:
y_pred = classifier_svm_rbf.predict(x_test)

In [99]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  2,  9]], dtype=int64)

In [100]:
28/30

0.9333333333333333

In [105]:
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel='poly')
classifier_svm_poly.fit(x_train, y_train)

SVC(kernel='poly')

In [106]:
y_pred = classifier_svm_poly.predict(x_test)

In [107]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 10]], dtype=int64)

In [108]:
29/30

0.9666666666666667

In [110]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [111]:
y_pred = classifier_svm_poly.predict(x_test)

In [113]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 10]], dtype=int64)

In [114]:
29/30

0.9666666666666667

In [120]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=3, criterion='entropy')
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [125]:
y_pred = classifier_rf.predict(x_test)

In [126]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 10]], dtype=int64)

In [127]:
29/30

0.9666666666666667