In [12]:
import numpy as np
import pandas as pd

In [3]:
a = [12,34,55]

np.array(a)

array([12, 34, 55])

In [5]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

demo_matrix[2,3]

39

In [6]:
demo_array=np.arange(0,10)

In [8]:
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.max(demo_array)

9

In [10]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

test_array[2:3]

[12]

In [13]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [15]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [ ]:
demo_matrix[:, (1,2)]

In [16]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [17]:
s1 = pd.Series(['a', 'b'])

s2 = pd.Series(['c', 'd'])

In [20]:
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object